name: '[net] Build client-gen-dotnet'

on:
  workflow_dispatch:

jobs:
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add aarch64-unknown-linux-gnu
      - run: cargo build -p sails-client-gen --release --target aarch64-unknown-linux-gnu
